# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMostrarmas():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_mostrarmas(self):
    self.driver.get("https://open.spotify.com/artist/7MPGCB854Qo4alYMOPkBka")
    self.driver.set_window_size(1900, 1020)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".nUpwbkL4Yaj31N0emCvb > .gvMYy0vqOxuYtbOkc6sH").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".nUpwbkL4Yaj31N0emCvb > .gvMYy0vqOxuYtbOkc6sH")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
